# -*- coding: utf-8 -*-
"""
Constants for MDA HR Module
Centralized definitions for salary grades and other lookup values
"""

SALARY_GRADE_LEVELS = [
    ('conhess_01', 'CONHESS 01'),
    ('conhess_02', 'CONHESS 02'),
    ('conhess_03', 'CONHESS 03'),
    ('conhess_04', 'CONHESS 04'),
    ('conhess_05', 'CONHESS 05'),
    ('conhess_06', 'CONHESS 06'),
    ('conhess_07', 'CONHESS 07'),
    ('conhess_08', 'CONHESS 08'),
    ('conhess_09', 'CONHESS 09'),
    ('conhess_10', 'CONHESS 10'),
    ('conhess_11', 'CONHESS 11'),
    ('conhess_12', 'CONHESS 12'),
    ('conhess_13', 'CONHESS 13'),
    ('conhess_14', 'CONHESS 14'),
    ('conhess_15', 'CONHESS 15'),
    ('contopsal_4', 'CONTOPSAL 4'),
    ('conmess_01', 'CONMESS 01'),
    ('conmess_02', 'CONMESS 02'),
    ('conmess_03', 'CONMESS 03'),
    ('conmess_04', 'CONMESS 04'),
    ('conmess_05', 'CONMESS 05'),
    ('conmess_06', 'CONMESS 06'),
    ('conmess_07', 'CONMESS 07'),
    ('conmess_08', 'CONMESS 08'),
    ('conmess_09', 'CONMESS 09'),
    ('conmess_10', 'CONMESS 10'),
]

NIGERIAN_STATES = [
    ('abia', 'Abia'),
    ('adamawa', 'Adamawa'),
    ('akwa_ibom', 'Akwa Ibom'),
    ('anambra', 'Anambra'),
    ('bauchi', 'Bauchi'),
    ('bayelsa', 'Bayelsa'),
    ('benue', 'Benue'),
    ('borno', 'Borno'),
    ('cross_river', 'Cross River'),
    ('delta', 'Delta'),
    ('ebonyi', 'Ebonyi'),
    ('edo', 'Edo'),
    ('ekiti', 'Ekiti'),
    ('enugu', 'Enugu'),
    ('fct', 'Federal Capital Territory'),
    ('gombe', 'Gombe'),
    ('imo', 'Imo'),
    ('jigawa', 'Jigawa'),
    ('kaduna', 'Kaduna'),
    ('kano', 'Kano'),
    ('katsina', 'Katsina'),
    ('kebbi', 'Kebbi'),
    ('kogi', 'Kogi'),
    ('kwara', 'Kwara'),
    ('lagos', 'Lagos'),
    ('nasarawa', 'Nasarawa'),
    ('niger', 'Niger'),
    ('ogun', 'Ogun'),
    ('ondo', 'Ondo'),
    ('osun', 'Osun'),
    ('oyo', 'Oyo'),
    ('plateau', 'Plateau'),
    ('rivers', 'Rivers'),
    ('sokoto', 'Sokoto'),
    ('taraba', 'Taraba'),
    ('yobe', 'Yobe'),
    ('zamfara', 'Zamfara'),
]

GEO_POLITICAL_ZONE_MAPPING = {
    'benue': 'north_central', 'fct': 'north_central', 'kogi': 'north_central',
    'kwara': 'north_central', 'nasarawa': 'north_central', 'niger': 'north_central',
    'plateau': 'north_central',
    'adamawa': 'north_east', 'bauchi': 'north_east', 'borno': 'north_east',
    'gombe': 'north_east', 'taraba': 'north_east', 'yobe': 'north_east',
    'jigawa': 'north_west', 'kaduna': 'north_west', 'kano': 'north_west',
    'katsina': 'north_west', 'kebbi': 'north_west', 'sokoto': 'north_west',
    'zamfara': 'north_west',
    'abia': 'south_east', 'anambra': 'south_east', 'ebonyi': 'south_east',
    'enugu': 'south_east', 'imo': 'south_east',
    'akwa_ibom': 'south_south', 'bayelsa': 'south_south', 'cross_river': 'south_south',
    'delta': 'south_south', 'edo': 'south_south', 'rivers': 'south_south',
    'ekiti': 'south_west', 'lagos': 'south_west', 'ogun': 'south_west',
    'ondo': 'south_west', 'osun': 'south_west', 'oyo': 'south_west',
}
